version: '3.9'
services:
  backend:
    build: ./backend
    container_name: knowledgehub_backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    container_name: knowledgehub_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    restart: always
