
services:
  backend:
    build: ./backend
    container_name: knowledgehub_backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: always
    networks:
      - knowledgehub-network

  frontend:
    build: ./frontend
    container_name: knowledgehub_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: always
    networks:
      - knowledgehub-network

networks:
  knowledgehub-network:
    driver: bridge
