const mongoose = require('mongoose');

const articleSchema = new mongoose.Schema({
  title: {
    type: String,
    required: [true, 'Title is required'],
    trim: true
  },
  content: {
    type: String,
    required: [true, 'Content is required']
  },
  tags: {
    type: [String],
    default: []
  },
  summary: {
    type: String,
    required: false, // Summary is optional - can be generated by AI
    trim: true,
    maxlength: [500, 'Summary cannot exceed 500 characters']
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  version: {
    type: Number,
    default: 1
  }
}, {
  timestamps: true
});

// Index for better search performance
// Note: Text index only on title and content. Tags uses regular index for array support.
articleSchema.index({ title: 'text', content: 'text' });
articleSchema.index({ tags: 1 }); // Separate index for tags array

module.exports = mongoose.model('Article', articleSchema);
